name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependências originais e novas
  http: ^1.2.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  cupertino_icons: ^1.0.6
  
  # Dependências para o banco de dados local
  sqflite: ^2.3.3
  path: ^1.9.0

  # >>> ADICIONE ESTA LINHA <<<
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
