name: Build Debug APK and Publish to Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Verificar APK gerado
        run: ls -lh build/app/outputs/flutter-apk/

      - name: Deletar release e tag antigas (latest)
        run: |
          gh release delete latest -y || true
          git tag -d latest || true
          git push origin :refs/tags/latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Criar release e enviar APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "📦 Build automático (Debug)"
          body: "🚀 Nova versão de teste gerada automaticamente a partir da branch **main**."
          files: build/app/outputs/flutter-apk/app-debug.apk
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}